# Generated by Django 4.1.1 on 2022-12-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CentroClinico', '0003_rental'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
