# Generated by Django 4.1 on 2022-12-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CentroClinico', '0007_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
