# Generated by Django 4.1.3 on 2022-12-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentroClinico', '0008_delete_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointmentdate',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientemail',
            field=models.DateField(max_length=10),
        ),
    ]
