# Generated by Django 4.1.1 on 2022-12-06 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CentroClinico', '0010_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctorname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CentroClinico.doctor'),
        ),
    ]
