# Generated by Django 4.1 on 2022-12-07 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CentroClinico', '0011_alter_appointment_doctorname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('specialization', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctorname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CentroClinico.doctore'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
