# Generated by Django 4.1 on 2022-12-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CentroClinico', '0012_doctore_alter_appointment_doctorname_delete_doctor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctore',
            new_name='Doctor',
        ),
    ]
