# Generated by Django 4.1.4 on 2022-12-10 23:23

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Nombre corto que se utilizara para indentificarse de manera unica en la plataforma.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'User not valid. Este campo debe contener letras, números y los siguientes carácteres: @/./+/-/_.', 'invalid')], verbose_name='Usuario'),
        ),
    ]
