# Generated by Django 4.1 on 2022-12-13 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='consultingroom',
        ),
    ]
