# Generated by Django 4.1.4 on 2022-12-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_diary_unique_together_and_more'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('diary', 'patient', 'consultingroom')},
        ),
    ]
