# Generated by Django 4.1 on 2022-12-13 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import doctors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultingroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Consultory 1'), ('2', 'Consultory 2')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('speciality', models.CharField(max_length=200, verbose_name='Speciality')),
                ('consultingroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctors.consultingroom')),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Ingrese una fecha', validators=[doctors.models.validate_day])),
                ('schedule', models.CharField(choices=[('1', '07:00 a 08:00'), ('2', '08:00 a 09:00'), ('3', '09:00 a 10:00'), ('4', '10:00 a 11:00'), ('5', '11:00 a 12:00')], max_length=10)),
                ('consultingroom', models.CharField(choices=[('1', 'Consultory 1'), ('2', 'Consultory 2')], max_length=15)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary', to='doctors.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'unique_together': {('schedule', 'day')},
            },
        ),
    ]
