# Generated by Django 4.1 on 2022-12-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='consultingroom',
        ),
        migrations.AlterField(
            model_name='consultingroom',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
