# Generated by Django 4.1.4 on 2022-12-12 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diary',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='diary',
            name='consultingroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary', to='doctors.consultingroom'),
        ),
        migrations.AlterUniqueTogether(
            name='diary',
            unique_together={('day', 'schedule', 'consultingroom')},
        ),
    ]
