# Generated by Django 4.1.4 on 2022-12-10 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Speciality',
            new_name='Consultingroom',
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultingroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctors.consultingroom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(max_length=200, verbose_name='Speciality'),
        ),
    ]
