# Generated by Django 4.1.4 on 2022-12-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_diary_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diary',
            unique_together={('day', 'schedule')},
        ),
        migrations.AlterField(
            model_name='diary',
            name='consultingroom',
            field=models.CharField(choices=[('1', 'Consultory 1'), ('2', 'Consultory 2'), ('3', 'Consultory 3'), ('4', 'Consultory 4'), ('5', 'Consultory 5')], max_length=15),
        ),
    ]
